[package]
name = "imm-cmp-hash"
version = "0.1.0"
authors = ["calibraint"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
img_hash = "3.1.0"
